#My Matrix learning

##Types of matrix

###Diagonal matrix

In [81]:
import numpy as np
diagonal_matrix = np.array([[1,0,0],[0,3,0],[0,0,2]])
print('Diagonal matrix:')
print(diagonal_matrix)

print('\nDiagonal matrix using numpy:')
print(np.diag([1,3,2]))


Diagonal matrix:
[[1 0 0]
 [0 3 0]
 [0 0 2]]

Diagonal matrix using numpy:
[[1 0 0]
 [0 3 0]
 [0 0 2]]


###Upper triangular matrix

In [82]:
upper_triangular_matrix=np.array ([[1,2,3],[0,5,6],[0,0,7]])
print('Upper triangular matrix:')
print(upper_triangular_matrix)
print('\nUpper triangular matrix using numpy:')
print(np.triu([[1,2,3],[4,5,6],[7,8,9]],0))

Upper triangular matrix:
[[1 2 3]
 [0 5 6]
 [0 0 7]]

Upper triangular matrix using numpy:
[[1 2 3]
 [0 5 6]
 [0 0 9]]


###Lower triangular matrix

In [83]:
lower_triangular_matrix=np.array([[1,0,0],[2,3,0],[4,5,6]])
print('Lower triangular matrix:')
print(lower_triangular_matrix)
print('\nLower triangular matrix using numpy:')
print(np.tril([[1,2,3],[4,5,6],[7,8,9]],0))

Lower triangular matrix:
[[1 0 0]
 [2 3 0]
 [4 5 6]]

Lower triangular matrix using numpy:
[[1 0 0]
 [4 5 0]
 [7 8 9]]


###Zero matrix

In [84]:
zero_matix = np.array([[0,0,0],[0,0,0],[0,0,0]])
print('Zero matrix:')
print(zero_matix)
print('\nZero matrix using numpy:')
print(np.zeros((3,3),int))

Zero matrix:
[[0 0 0]
 [0 0 0]
 [0 0 0]]

Zero matrix using numpy:
[[0 0 0]
 [0 0 0]
 [0 0 0]]


###Identity matrix

In [85]:
identity_matrix = np.array([[1,0,0],[0,1,0],[0,0,1]])
print('Identity matrix:')
print(identity_matrix)
print('\nIdentity matrix using numpay:')
print(np.identity(3,int))

Identity matrix:
[[1 0 0]
 [0 1 0]
 [0 0 1]]

Identity matrix using numpay:
[[1 0 0]
 [0 1 0]
 [0 0 1]]


##Vector Algebra


###Addition or substraction
Addition or substraction of martix only possible if size(dimention) of matrix is same.
M1 + M2 = M2 + M1
M1 - M2 2260 M1 - M2

In [86]:
first_matrix = np.array([[1,3],[1,3]])
second_matrix = np.array([[1,1],[1,2]])
print('Matrix 1:')
print(first_matrix)
print('\n')
print('Matrix 2:')
print(second_matrix)
print('\n')
sum_matrix = first_matrix + second_matrix
substraction_matrix = first_matrix - second_matrix
print('Addition of matrix')
print(sum_matrix)
print('\n')
print('Addition of matrix using numpay')
print(np.add(first_matrix,second_matrix))
print('\n')
print('Substraction of matrix')
print(substraction_matrix)
print('\n')
print('Substraction of matrix using numpy')
print(np.subtract(first_matrix, second_matrix))


Matrix 1:
[[1 3]
 [1 3]]


Matrix 2:
[[1 1]
 [1 2]]


Addition of matrix
[[2 4]
 [2 5]]


Addition of matrix using numpay
[[2 4]
 [2 5]]


Substraction of matrix
[[0 2]
 [0 1]]


Substraction of matrix using numpy
[[0 2]
 [0 1]]


###Multiplication
Multiplication of matrix is only posssible if first matrics columns number is same os number of rows of second matrix


In [87]:
import numpy as np
mul_matrix1= np.array([[1,3,1],[-1,5,2]])
mul_matrix2 = np.array([[1,5],[3,2],[-1,0]])
print('Matrix 1:')
print(mul_matrix1)
print('\n')
print('Matrix 2:')
print(mul_matrix2)
m11 = (1 * 1) +(3 * 3) + (1*-1)     # mul_matrix1[0][0] * mul_matrix2[0][0] + mul_matrix1[0][1] * mul_matrix2[1][0] + mul_matrix1[0][2] * mul_matrix2[2][0]
m12 = (1 * 5) +(3 * 2) + (1*0)      # mul_matrix1[0][0] * mul_matrix2[0][1] + mul_matrix1[0][1] * mul_matrix2[1][1] + mul_matrix1[0][2] * mul_matrix2[2][1]
m21 =  (-1 * 1) + (5 * 3) + (2*-1)  # mul_matrix1[1][0] * mul_matrix2[0][0] + mul_matrix1[1][1] * mul_matrix2[1][0] + mul_matrix1[1][2] * mul_matrix2[2][0]
m22 =  (-1 * 5) +(5 * 2) + (2*0)    # mul_matrix1[1][0] * mul_matrix2[0][1] + mul_matrix1[1][1] * mul_matrix2[1][1] + mul_matrix1[1][2] * mul_matrix2[2][1]
matrix_mul = np.matrix([[m11,m12],[m21,m22]])
print('\n')
print('Multiplication of matrix using calcualtion:')
print(matrix_mul)
#using funtion
print('\n')
mul_matrix = np.dot(mul_matrix1, mul_matrix2)
print('Multiplication of matrix using numpy:')
print(mul_matrix)


Matrix 1:
[[ 1  3  1]
 [-1  5  2]]


Matrix 2:
[[ 1  5]
 [ 3  2]
 [-1  0]]


Multiplication of matrix using calcualtion:
[[ 9 11]
 [12  5]]


Multiplication of matrix using numpy:
[[ 9 11]
 [12  5]]


###Transpose of Matrix
Rules:

$(A+B)^T = A^T + B^T$

$(AB)^T =B^T A^T$

$(kA)^T =kA^T$

$(A^T)^T =A$



In [88]:
m1= np.array([[1,3,1],[-1,5,2]])
print('Matrix:')
print(m1)
transpose =np.transpose(m1)
print('\nTranspose of matrix')
print(transpose)

Matrix:
[[ 1  3  1]
 [-1  5  2]]

Transpose of matrix
[[ 1 -1]
 [ 3  5]
 [ 1  2]]


###Determinant of matrix

In [89]:
import numpy as np
determinant_example_matrix = np.array([[1,-1],[2,3]])
print('Matrix:')
print(determinant_example_matrix)
det_calculated = 1*3 - (2*-1) #determinant_example_matrix[0][0] * determinant_example_matrix[1][1] - determinant_example_matrix[0][1]* determinant_example_matrix[1][0]
print('\nDeterminant of matrix using calculation:',det_calculated)
det_using_np = np.linalg.det(determinant_example_matrix)
print('\nDeterminant of matrix using numpy:', int(det_using_np))


Matrix:
[[ 1 -1]
 [ 2  3]]

Determinant of matrix using calculation: 5

Determinant of matrix using numpy: 5


###Inverse of a matrix
If determinant is zero then inverse is not define

Rules:

$(AB)^-1$ = $B^-1 A^-1$

$(A^-1)^-1 = A$

$(A^T)^-1  = (A^-1)^T$

$(kA)^-1  = 1/k (A)^-1$



In [90]:
import numpy as np
import math
inverse_example_matrix = np.array([[1,-1],[2,3]])

det = np.linalg.det(inverse_example_matrix)

m11 = (1/det) * 3   # (1/det) * inverse_example_matrix[1][1]
m12 = (1/det) * 1   # (1/det) * -(inverse_example_matrix[0][1])
m21 = (1/det) * -2  # (1/det) * -(inverse_example_matrix[1][0])
m22 = (1/det) * 1   # (1/det) * inverse_example_matrix[0][0]
calculated_inverse = np.array([[m11,m12],[m21,m22]])
print('Inverse of matrix using calculations')
print(calculated_inverse)
print('\n')
print('Inverse of matrix using numpy')
print(np.linalg.inv(inverse_example_matrix))


Inverse of matrix using calculations
[[ 0.6  0.2]
 [-0.4  0.2]]


Inverse of matrix using numpy
[[ 0.6  0.2]
 [-0.4  0.2]]
