#Numpy
NumPy is short from of numerical Python. Numpy is open source library.

NumPy operations are implemented in C and Fortan, making them faster than equivalent operations perfomed with standard Python lists(objects) especially for the large number of data.

NumPy used as foundation for many other important libraries like Pandas, SciPy, Matplotib, Scikit-learn.


##ndarray object
ndarray object is main feature of numpy whci provide support for multi dimensional array and matrices.

In [ ]:
import numpy as np
ndarray_object = np.array([1,2,3])
print(type(ndarray_object))


<class 'numpy.ndarray'>


##Arithmetic operations




###Addition

In [ ]:
matrix_1 = np.array([1,2,3])
matrix_2 = np.array([4,5,6])

print('Addition of Matrix\n', np.add(matrix_1,matrix_2))

Addition of Matrix
 [5 7 9]


###Subtraction





In [ ]:
print('\nSubtraction of Matrix\n', np.subtract(matrix_1,matrix_2))


Subtraction of Matrix
 [-3 -3 -3]


###Multiplication

In [ ]:
print('\nMultiplication of Matrix\n', np.multiply(matrix_1,matrix_2))



Multiplication of Matrix
 [ 4 10 18]


###Division

In [ ]:
print('Division of Matrix\n', np.divide(matrix_1,matrix_2))

Division of Matrix
 [0.25 0.4  0.5 ]


###Modulus

In [ ]:
print("Modulus (function)\n", np.mod(matrix_1,matrix_2))

Modulus (function)
 [1 2 3]


###Exponentiation

In [ ]:
print(np.power(matrix_1,2))

[1 4 9]


##Accessing and modifying NumPy arrays

###Random number array

In [ ]:
import numpy as np
random_array = np.random.rand(8)
print("Random number array:\n",random_array)

random_number_matrix = np.random.rand(5,5)

print('\nRandom number array :\n',random_number_matrix)

print('\nFilter based on number of row and column\n', random_number_matrix[0:2,1:3])

random_number_matrix[2:5][ 1:5]= 5

print('\nRandom number array after set:\n',random_number_matrix)

Random number array:
 [0.19536928 0.67115609 0.67044563 0.46371879 0.51713576 0.63816734
 0.97179002 0.55994615]

Random number array :
 [[0.72079652 0.48559734 0.02111821 0.34364865 0.55771593]
 [0.50455629 0.16684495 0.19442435 0.53123821 0.26867661]
 [0.75504076 0.41606077 0.80221688 0.77707222 0.90748647]
 [0.48084728 0.38934618 0.78366689 0.66932884 0.98405969]
 [0.99515107 0.59887671 0.23805832 0.42806101 0.02349298]]

Filter based on number of row and column
 [[0.48559734 0.02111821]
 [0.16684495 0.19442435]]

Random number array after set:
 [[0.72079652 0.48559734 0.02111821 0.34364865 0.55771593]
 [0.50455629 0.16684495 0.19442435 0.53123821 0.26867661]
 [0.75504076 0.41606077 0.80221688 0.77707222 0.90748647]
 [5.         5.         5.         5.         5.        ]
 [5.         5.         5.         5.         5.        ]]


###Arange array

In [ ]:
arange_array = np.arange(100, 220, 50)
print("Arange array:\n",arange_array)
print("Array filter with condition\n",arange_array[arange_array<=150])


Arange array:
 [100 150 200]
Array filter with condition
 [100 150]


In [ ]:
rand_matrix =  np.random.rand(10)

print(rand_matrix)

rand_matrix = np.arange(33)
print(rand_matrix)

[0.49025957 0.76220144 0.08030541 0.68571858 0.48701656 0.57715213
 0.15778415 0.91274977 0.19115961 0.2277346 ]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32]
